name: Build and Test

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - main

jobs:
    
    build:
        
        strategy:
            matrix:
                dotnet-version: ['6.0.x', '7.0.x']
                os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

        runs-on: ${{ matrix.os }}

        steps:
            - name: checkout repository
              uses: actions/checkout@v2

            - name: setup .net${{ matrix.dotnet-version }}
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: ${{ matrix.dotnet-version }}
            
            - name: restore dependencies
              run: dotnet restore
            
            - name: build solution
              run: dotnet build --configuration Release

            - name: run tests
              run: dotnet test --configuration Release --no-build