name: Build and Test

on:
    push:
    pull_request:
        branches:
            - main

jobs:
    
    build:
        
        strategy:
            matrix:
                dotnet-version: ['7.0.x']
                os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

        runs-on: ${{ matrix.os }}

        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            
            #check the github branch base branch
            - name: print branch name
              run: |
                echo branch name is ${{ github.base_ref }}

            - name: setup .net${{ matrix.dotnet-version }}
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: ${{ matrix.dotnet-version }}
            
            - name: restore dependencies
              run: dotnet restore
            
            - name: build solution
              run: dotnet build --configuration Release

            - name: run tests
              run: dotnet test --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"

            - name: upload .net test results
              uses: actions/upload-artifact@v3
              with:
                name: dotnet-results-${{ matrix.dotnet-version }}
                path: TestResults-${{ matrix.dotnet-version }}
              if: ${{ always() }}
              
            - name: change version
              run: |
                dotnet tool install -g dotnet-version-cli
                dotnet version -f ./PrimeService/PrimeService.csproj patch
              if: ${{ github.ref == 'refs/heads/main' }}
